###The installation step consists solely of installing the MicroStack snap across all compute hosts
---
- hosts: compute
  tasks:
  - name: sudo microstack init --auto --control
    snap:
      name: microstack
      channel: beta --devmode
